sudo: required

services:
  - docker

before_install:
  - docker build -t haris/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true haris/react-test npm run test

after_success:
  - docker build -t haris/multi-client -f ./client
  - docker build -t haris/multi-nginx ./nginx
  - docker build -t haris/multi-server ./server
  - docker build -t haris/multi-worker ./worker
  #Push the images to Docker Hub



