sudo: required

services:
  - docker

before_install:
  - docker build -t harisnp/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true harisnp/react-test npm run test

after_success:
  - docker build -t harisnp/multi-client ./client
  - docker build -t harisnp/multi-nginx ./nginx
  - docker build -t harisnp/multi-server ./server
  - docker build -t harisnp/multi-worker ./worker
  #Push the images to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push harisnp/multi-client
  - docker push harisnp/multi-nginx
  - docker push harisnp/multi-server
  - docker push harisnp/multi-worker




